const products = [
    {
        _id: 1,
        name: 'Romper',
        image: '/images/romper.jpg',
        description: 'A effortless jumpsuit. Adorable lightweight fabric in a feminine design, making this romper a great option for effortless style this all year long.',
        brand: 'Aston Jeremiah',
        category: 'Casual',
        price: 84.99,
        leftInStock: 6,
        Reviews: 5,
        rating: 4.9,
    },
    {
        _id: 2,
        name: 'Dress',
        image: '/images/dress.jpg',
        description: 'A strapless dress, bodice style sleeveless dress with neckline and thin shoulder straps.',
        brand: 'Aston Jeremiah',
        category: 'Casual',
        price: 96.99,
        leftInStock: 10,
        Reviews: 9,
        rating: 5,
    },
    {
        _id: 3,
        name: 'Shoes',
        image: '/images/shoes.jpg',
        description: 'A versatile shoe, which can be worn any season.',
        brand: 'Aston Jeremiah',
        category: 'Casual',
        price: 76.99,
        leftInStock: 8,
        Reviews: 5,
        rating: 5,
    },
]

export default products